### ISSUE TITLE
ClientSession is not re-established on error

### ISSUE THREAD

**Issue by CookieJ4R** [CookieJ4R/LIS#15]
When the ClientSession fails (like when my ISP has **_another_** Outage) all outgoing requests (like weather data, calendar data, ...) will fail and will not work until the Program is restarted.

A failsafe should be implemented that will try to re-create the ClientSession periodically if it fails.

**Comment by IchBinderKevin** [comment]
Fixed by making use of a shared session that is re-created if the previous session was closed. Time will tell if it works as it should now.
